//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameSystem.Models
{
    using System;
    using System.Collections.Generic;
    //
    using System.ComponentModel.DataAnnotations;
    public partial class Msg
    {
        public int MsgID { get; set; }
        [Display(Name = "标题:")]
        [Required(ErrorMessage = "{0}是必填项")]
        public string MsgTitle { get; set; }
        [Display(Name = "内容:")]
        [Required(ErrorMessage = "{0}是必填项")]
        public string MsgText { get; set; }
        [Display(Name = "类型:")]
        [Required(ErrorMessage = "{0}是必填项")]
        public string MsgType { get; set; }
        [Display(Name = "图片:")]
        public string MsgPhoto { get; set; }
        [Display(Name = "时间:")]
        public System.DateTime MsgTime { get; set; }
        [Display(Name = "点击数:")]
        public Nullable<int> MsgHit { get; set; }
        [Display(Name = "发布人ID:")]
        public Nullable<int> AccountID { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
